### ISSUE TITLE
My button setup

### ISSUE THREAD

**Issue by danishru** [Flumeded/esphome-SK23-Nebula-Light#1]
The button didn't work for me either. Here's part of the code to make it work.I also had a button that didn't work. Here's part of the code to make it work. Also, the LEDs in my SK20 are not controlled, they are just constantly powered by 3.3v. That's why I turned off the button_led0_gpio pin.

![image](https://github.com/user-attachments/assets/b9678fd4-3da0-46d9-8029-b20aac2a728b)

**Comment by Flumeded** [comment]
Thank you @danishru, I implemented your pinout config in my yml!
